ignore:
  - "examples"
  - "pb"

coverage:
  ignore:
    - "examples"
    - "pb"
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true